INSERT INTO tbl_todo(username, description, target_date, done) VALUES ('setianjay', 'Learn Kotlin', '2023-03-13', false)
INSERT INTO tbl_todo(username, description, target_date, done) VALUES ('setianjay', 'Learn Java', '2023-03-13', false)
INSERT INTO tbl_todo(username, description, target_date, done) VALUES ('setianjay', 'Learn Android', '2023-03-13', false)
INSERT INTO tbl_todo(username, description, target_date, done) VALUES ('setianjay', 'Learn Fullstack Dev', '2023-03-13', false)
INSERT INTO tbl_todo(username, description, target_date, done) VALUES ('gurindo', 'Learn SQL', '2023-03-13', false)
INSERT INTO tbl_todo(username, description, target_date, done) VALUES ('gurindo', 'Learn Network', '2023-03-13', false)